### ISSUE TITLE
please add samples of input +  output

### ISSUE THREAD

**Issue by aspiringguru** [Hardik-26/Filter-A-Tor#1]
just found this. Looks to have potential. 
Can you do some sample videos to show how it performs? and/or some notes on what you think needs doing to improve this product?  

if you chugged this out in 14hrs, I'm curious what might be achieved with more eyes on the code.

otherwise thanks for sharing.

**Comment by Hardik-26** [comment]
### Hi, aspiringguru.

Thank you soo must for recognising my code, it means a lot to me.
I will add some input and output sample videos within the next few days.
as for the thing that can be improved-
I threw this code together in 14hrs so many variables are not proper, hence I could clean up my code a bit and re-write it according to PEP8 standards.
I could also try and figure out a way to incorporate the 'del.py' file into one whole python program.

#### Please feel free to give out any suggestions on how I can improve this product.

#### Thank you.
